# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: twitch-darwin
    ldflags: 
      - -s -w -X main.buildVersion={{ .Version }} 
    binary: twitch
    env:
      - CGO_ENABLED=1  
      - CC=o64-clang 
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
  - id: twitch-linux
    ldflags:
      - -s -w -X main.buildVersion={{ .Version }}
    binary: twitch
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
  - id: twitch-windows-x64
    ldflags: 
    - -s -w -X main.buildVersion={{ .Version }} 
    binary: twitch
    main: ./main.go
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
  - id: twitch-windows-i386
    ldflags:
      - -s -w -X main.buildVersion={{ .Version }} 
    binary: twitch
    main: ./main.go
    env:
      - CGO_ENABLED=1
      - CC=i686-w64-mingw32-gcc-posix
      - CXX=i686-w64-mingw32-g++-posix
    goos:
      - windows
    goarch:
      - 386
scoop:
  bucket:
    owner: twitchdev
    name: scoop-bucket
  homepage: https://github.com/twitchdev/twitch-cli
  description: CLI for Twitch's developer offerings
  license: Apache-2.0
brews:
  -
    tap:
      owner: twitchdev
      name: homebrew-twitch
    folder: Formula
    homepage: https://github.com/twitchdev/twitch-cli
    description: CLI for Twitch's developer offerings
    custom_block: | 
      if OS.mac? && Hardware::CPU.arm?
        url "https://github.com/twitchdev/twitch-cli.git", tag: "{{ .Tag }}"
        depends_on "go" => :build
      end

      head "https://github.com/twitchdev/twitch-cli.git", branch: "main"
      head do
        depends_on "go" => :build
      end
    install: |
      v = version
      if build.head? 
        v = "head"
        ldflags = "-X main.buildVersion=#{v}"
        system "go", "build", "-ldflags=#{ldflags}"
        mv "twitch-cli", "twitch"
      end

      if OS.mac? && Hardware::CPU.arm? 
        ldflags = "-X main.buildVersion=#{v}"
        system "go", "build", "-ldflags=#{ldflags}"
        mv "twitch-cli", "twitch"
      end
      
      bin.install "twitch"
    test: |
      system "#{bin}/twitch", "version"
    license: Apache-2.0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
